// GENERATED CODE - DO NOT MODIFY BY HAND
// This file will be generated by build_runner
//
// To generate this file, run:
// flutter pub run build_runner build --delete-conflicting-outputs
//
// The generated code will look like:
// GetIt getIt = GetIt.instance;
// Future<void> configureDependencies() async {
//   getIt.registerFactory<AuthRepository>(() => AuthRepositoryImpl(...));
//   getIt.registerFactory<TaskRepository>(() => TaskRepositoryImpl(...));
//   // ... other registrations
// }
